//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sinhvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sinhvien()
        {
            this.lophocs = new HashSet<lophoc>();
            this.bangdiems = new HashSet<bangdiem>();
        }
    
        public string MaSv { get; set; }
        public string HoSv { get; set; }
        public string TenSv { get; set; }
        public string Diachi { get; set; }
        public string Email { get; set; }
        public string Sdt { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string Nganh { get; set; }
        public string Tentruong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lophoc> lophocs { get; set; }
        public virtual Nganhhoc1 Nganhhoc1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bangdiem> bangdiems { get; set; }
        public virtual Truong Truong { get; set; }
    }
}
